name: peerstash-test
x-meta:
  compose_version: 0.9.0
services:
  storage:
    image: drakkan/sftpgo:v2-alpine-slim
    container_name: peerstash-sftp-test
    network_mode: service:control
    environment:
      - SFTPGO_SFTPD__PASSWORD_AUTHENTICATION=false
      - SFTPGO_SFTPD__KEYBOARD_INTERACTIVE_AUTHENTICATION=false
      - SFTPGO_HTTPD__BINDINGS__0__ADDRESS=127.0.0.1
      - SFTPGO_HTTPD__BINDINGS__0__ENABLE_WEB_ADMIN=0
      - SFTPGO_HTTPD__BINDINGS__0__ENABLE_WEB_CLIENT=0
      - SFTPGO_DATA_PROVIDER__CREATE_DEFAULT_ADMIN=true
      - SFTPGO_DEFAULT_ADMIN_USERNAME=admin
      - SFTPGO_DEFAULT_ADMIN_PASSWORD=adminpass
    volumes:
      - type: bind
        source: ../.test/peerstash_test_sftp/data
        target: /srv/sftpgo/data
        bind:
          create_host_path: true
      - type: bind
        source: ../.test/peerstash_test_sftp/config
        target: /var/lib/sftpgo
        bind:
          create_host_path: true
    depends_on:
      - control
    restart: unless-stopped

  control:
    build: ../peerstash-control
    container_name: peerstash-control-test
    network_mode: bridge
    hostname: peerstash-test-admin
    environment:
      - USERNAME=admin
      - PASSWORD=adminpass
      - DEFAULT_QUOTA_GB=10
      - TZ=UTC
    volumes:
      - type: bind
        source: ../.test/peerstash_test_root
        target: /mnt/peerstash_root
      - type: bind
        source: ../.test/peerstash_test_control/config
        target: /var/lib/peerstash
        bind:
          create_host_path: true
      - type: bind
        source: ../.test/peerstash_test_control/data
        target: /srv/peerstash/data
        bind:
          create_host_path: true
      - type: bind
        source: ../.test/peerstash_test_restore
        target: /mnt/peerstash_restore
        bind:
          create_host_path: true
      - type: bind
        source: ../.test/peerstash_test_control/data/restic_cache
        target: /root/.cache/restic
        bind:
          create_host_path: true
      # Mount the codebase so we can run tests
      - type: bind
        source: ../peerstash-control
        target: /app/testing
        bind:
          create_host_path: true
    restart: unless-stopped
    command: ["tail", "-f", "/dev/null"] # Keep container alive for tests
