import subprocess
from unittest.mock import MagicMock, mock_open

import pytest
from pytest_mock import MockerFixture

from peerstash.core.utils import (Retention, acquire_task_lock,
                                  gen_restic_pass, generate_sha1,
                                  get_disk_usage, get_file_content,
                                  release_lock, send_to_daemon, sizeof_fmt,
                                  update_crontab, validate_paths,
                                  validate_retention, validate_schedule,
                                  validate_task_name, verify_sudo_password)

# --- Pure Functions & String Manipulation ---


def test_sizeof_fmt():
    assert sizeof_fmt(1023) == "1023.0B"
    assert sizeof_fmt(1024) == "1.0KiB"
    assert sizeof_fmt(1048576) == "1.0MiB"
    assert sizeof_fmt(1073741824) == "1.0GiB"


def test_generate_sha1():
    # Known SHA-1 hash for "test"
    assert generate_sha1("test") == "a94a8fe5ccb19ba61c4c0873d391e987982fbbd3"


def test_validate_task_name():
    assert validate_task_name("valid-task_name123") is None

    # Type narrowing to satisfy strict type checkers
    res1 = validate_task_name("invalid name!")
    assert res1 is not None
    assert "illegal characters" in res1

    res2 = validate_task_name("a" * 128)
    assert res2 is not None
    assert "too long" in res2


def test_validate_schedule():
    assert validate_schedule("0 4 * * 0") is True
    assert validate_schedule("0 4") is False
    assert validate_schedule("90 5 * * *") is False
    assert validate_schedule("invalid_cron") is False


def test_validate_paths():
    assert validate_paths(["/mnt/peerstash/data"]) is None
    assert validate_paths(["/mnt/peerstash/data", "/home/user"]) == "/home/user"


def test_validate_retention():
    # Valid formats
    assert validate_retention("1y2m3w4d5h6r") is None
    assert validate_retention("7d") is None

    # Invalid formats
    res2 = validate_retention("1y2y")
    assert res2 is not None
    assert "Duplicate unit" in res2
    
    res1 = validate_retention("1y2z")
    assert res1 is not None
    assert "Invalid retention string" in res1
    
    res1 = validate_retention("r")
    assert res1 is not None
    assert "Invalid retention string" in res1

    res3 = validate_retention("bad_string")
    assert res3 is not None
    assert "Invalid retention string" in res3


def test_retention_model_parsing():
    ret = Retention.from_string("1y2m3w4d5h6r")
    assert ret.yearly == 1
    assert ret.monthly == 2
    assert ret.weekly == 3
    assert ret.daily == 4
    assert ret.hourly == 5
    assert ret.recent == 6


# --- System Boundary Functions ---


def test_get_file_content_success(mocker: MockerFixture):
    mocker.patch("os.path.exists", return_value=True)
    m_open = mock_open(read_data="file_data\n")
    mocker.patch("builtins.open", m_open)

    content = get_file_content("/test/path")
    assert content == "file_data"


def test_get_file_content_missing(mocker: MockerFixture):
    mocker.patch("os.path.exists", return_value=False)
    assert get_file_content("/test/path") is None


def test_get_disk_usage_success(mocker: MockerFixture):
    mock_run = mocker.patch("subprocess.run")
    # Simulate the raw output of `df` returning KiB blocks: Total, Used, Available
    mock_run.return_value.stdout = "1000 300 700"

    total, used, free = get_disk_usage("alice", "host", 2022)
    assert total == 1024000  # 1000 * 1024
    assert used == 307200  # 300 * 1024
    assert free == 716800  # 700 * 1024


def test_get_disk_usage_failure(mocker: MockerFixture):
    mocker.patch("subprocess.run", side_effect=subprocess.CalledProcessError(1, "sftp"))
    with pytest.raises(RuntimeError, match="Could not get quota"):
        get_disk_usage("alice", "host", 2022)


def test_verify_sudo_password_success(mocker: MockerFixture):
    mock_run = mocker.patch("subprocess.run")
    verify_sudo_password("correct_pass")
    assert mock_run.call_count == 2  # Once for -k, once for -v


def test_verify_sudo_password_failure(mocker: MockerFixture):
    mocker.patch("subprocess.run", side_effect=subprocess.CalledProcessError(1, "sudo"))
    with pytest.raises(ValueError, match="Invalid admin password"):
        verify_sudo_password("wrong_pass")


def test_gen_restic_pass(mocker: MockerFixture):
    mock_unlink = mocker.patch("pathlib.Path.unlink")
    mock_write = mocker.patch("pathlib.Path.write_text")
    mock_chmod = mocker.patch("os.chmod")

    gen_restic_pass("alice", "admin123")

    mock_unlink.assert_called_once_with(missing_ok=True)
    mock_write.assert_called_once()
    assert "THIS PASSWORD WAS GENERATED BY PEERSTASH" in mock_write.call_args[0][0]
    mock_chmod.assert_called_once_with(mocker.ANY, 0o400)


def test_update_crontab_success(mocker: MockerFixture):
    mock_run = mocker.patch("subprocess.run")
    # Simulate existing crontab with one unrelated job and one peerstash job
    mock_run.return_value.stdout = "0 0 * * * unrelated_job\n0 4 * * * peerstash backup my_task 10"
    mock_run.return_value.returncode = 0

    success, msg = update_crontab("my_task", ["0 5 * * * new_job"])

    assert success is True
    # Verify the second subprocess call (crontab -) passed the unrelated job + the new job
    stdin_data = mock_run.call_args_list[1][1]["input"]
    assert "unrelated_job" in stdin_data
    assert "new_job" in stdin_data
    assert "peerstash backup my_task" not in stdin_data


def test_update_crontab_failure(mocker: MockerFixture):
    mocker.patch(
        "subprocess.run", side_effect=subprocess.CalledProcessError(1, "crontab")
    )
    success, msg = update_crontab("my_task")
    assert success is False
    assert "Crontab update failed" in msg


def test_acquire_and_release_lock(mocker: MockerFixture):
    mocker.patch("os.path.exists", return_value=True)
    m_open = mock_open()
    mocker.patch("builtins.open", m_open)
    mock_flock = mocker.patch("fcntl.flock")
    mocker.patch("os.getpid", return_value=9999)

    # Test Acquire
    lock_file = acquire_task_lock("test_bkp")
    mock_flock.assert_called_once()
    m_open().write.assert_called_once_with("9999")

    # Test Release
    release_lock(lock_file)
    assert mock_flock.call_count == 2
    m_open().close.assert_called_once()


def test_acquire_lock_blocking(mocker: MockerFixture):
    mocker.patch("os.path.exists", return_value=True)
    mocker.patch("builtins.open", mock_open())
    mocker.patch("fcntl.flock", side_effect=BlockingIOError())

    with pytest.raises(RuntimeError, match="already running in another process"):
        acquire_task_lock("test_bkp")


def test_send_to_daemon_success(mocker: MockerFixture):
    mock_socket = mocker.patch("socket.socket")
    mock_client = MagicMock()
    # Simulate daemon returning a valid JSON success response
    mock_client.recv.return_value = b'{"status": "success", "message": "Done"}'
    mock_socket.return_value.__enter__.return_value = mock_client

    response = send_to_daemon("create_task", {"task_name": "test"})

    assert response["status"] == "success"
    # Ensure payload was properly encoded and sent
    sent_data = mock_client.sendall.call_args[0][0].decode("utf-8")
    assert "create_task" in sent_data


def test_send_to_daemon_error_response(mocker: MockerFixture):
    mock_socket = mocker.patch("socket.socket")
    mock_client = MagicMock()
    mock_client.recv.return_value = b'{"status": "error", "message": "Bad request"}'
    mock_socket.return_value.__enter__.return_value = mock_client

    with pytest.raises(RuntimeError, match="Daemon Error: Bad request"):
        send_to_daemon("create_task")


def test_send_to_daemon_not_found(mocker: MockerFixture):
    mock_socket = mocker.patch("socket.socket")
    mock_socket.return_value.__enter__.side_effect = FileNotFoundError()

    with pytest.raises(RuntimeError, match="Daemon socket not found"):
        send_to_daemon("create_task")
