[supervisord]
nodaemon=true
user=root
logfile=/var/log/peerstash/supervisord.log
logfile_maxbytes=10MB
logfile_backups=5

[program:cron]
command=cron -f
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:sshd]
command=/srv/peerstash/start-sshd.sh
autostart=true
autorestart=true
stdout_logfile=/var/log/peerstash/sshd.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=3
stderr_logfile=/dev/null

[program:tail-logger]
command=tail -qF /var/log/peerstash/supervisord.log /var/log/peerstash/sshd.log /var/log/peerstash/peerstash.log
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:tailscaled]
command=/usr/local/bin/tailscaled --tun=peerstash0
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:peerstashd]
command=/usr/local/bin/peerstashd
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
